import SmullyanKnightsAndKnaves.knightsknaves

import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob26
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob27
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob28
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob29
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob30
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob31
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob32
import SmullyanKnightsAndKnaves.dsl_knightsknaves.prob34


import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob26
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob27
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob28
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob29
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob30
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob31
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob32
import SmullyanKnightsAndKnaves.knightsknaves_settheory.prob34
